version: "2"
engines:
  pmd:
    enabled: true
    config: config/appexRuleset.xml
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - ".forceignore"
  - ".gitignore"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "uipath-core/"
  - ".vscode/"
  - ".sfdx/"
  - ".idea/"
  - "scripts/"
  - ".github/"
  - "**/applications/"
  - "**/aura/"
  - "**/contentassets/"
  - "**/customMetadata/"
  - "**/customPermissions/"
  - "**/flexipages/"
  - "**/globalValueSets/"
  - "**/installedPackages/"
  - "**/layouts/"
  - "**/lwc/"
  - "**/objects/"
  - "**/permissionsets/"
  - "**/profiles/"
  - "**/standardValueSets/"
  - "**/staticresources/"
  - "**/tabs/"
